# Generated by Django 4.0.2 on 2022-02-21 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaluser',
            name='created',
        ),
    ]
