# Generated by Django 4.0.2 on 2022-02-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('date', models.DateField()),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=1500)),
                ('author', models.CharField(max_length=10)),
                ('id_number', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
