# Generated by Django 4.0.2 on 2022-02-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='password',
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
    ]
